import type { Metadata } from "next";
import { Bungee_Shade, Electrolize, Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout";
import { Footer } from "@/components/layout/footer";

const electrolize = Electrolize({
  variable: "--font-electrolize",
  weight: ["400"],
  subsets: ["latin"],
});

const luckiestGuy = Bungee_Shade({
  variable: "--font-bungee_shade",
  weight: "400",
  subsets: ["latin"],
});

const anta = Roboto({
  variable: "--font-anta",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL("https://jsonsformatter.com"),
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    card: "summary_large_image",
    title: `JSONs Formatter`,
    description: "",
    // siteId: "1467726470533754880",
    // creator: "@nextjs",
    // creatorId: "1467726470533754880",
    // images: ["https://nextjs.org/og.png"], // Must be an absolute URL
  },
  bookmarks: `https://jsonsformatter.com`,
  category: "Technology",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${electrolize.variable} ${luckiestGuy.variable} ${anta.variable} font-anta antialiased min-h-[100vh] bg-slate-50`}
      >
        <Header />
        <div className="min-h-[calc(100vh-55px)]">
          <main className="min-h-[calc(100vh-55px)]">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
